### ISSUE TITLE
Antwort

### ISSUE THREAD

**Issue by SoltauFintel** [champik86/FSD_MagicBlocks#1]
Du kannst mich anschreiben, wenn Du meine Emailadresse findest. ;-)

Meine Sourcen sind so schwer zu verstehen, weil es meine erste Android App ist. Ich bin derzeit dabei die Persistence und die Game-Engine umzubauen.

**Comment by SoltauFintel** [comment]
Ich empfehle Dir die App ID "de.mwvb.blockpuzzle" zu ändern, denn sonst kommt es zu einer Kollision mit meiner Block Puzzle Stone Wars App. (s. build.gradle)

**Comment by champik86** [comment]
Next week I'm  planning to code everything in new project. Your code helped me a lot. I made already the main logic, next week I hope I'm  gonna receive all the stuff from designers and gonna work on intarface.

**Comment by champik86** [comment]
I don't  understand why you made all the gamePieces in a string and then parse it ))It's so complicated ))

**Comment by champik86** [comment]
juni@mwvb.de  is this your e-mail?

**Comment by SoltauFintel** [comment]
Yes. Please remove it from your comment. (privacy)

GamePieces: do you have a better idea? It was before coded, but now it's visually designed. That help's.

**Comment by champik86** [comment]
GamePieces: I want to create just list of objects instead. 
Also I implemented shadow on the playingField when the gamePiece matches. It's popular now ))
